name: kigali_services_directory
description: Kigali Services & Places Directory App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

# firebase dependencies
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.5.6

# state management dependencies
  provider: ^6.1.1

# Maps & Location dependencies
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  url_launcher: ^6.2.1

# UI Components dependencies
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.3.0
  image_picker: ^1.0.5

# utility dependencies
  intl: ^0.18.1
  uuid: ^4.3.3

# dev dependencies
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true